# Adds lable to PR based on file changes

# C2 server files
c2servers:
  - 'c2servers/**/*'

# ELK server files
elkserver:
  - 'elkserver/**/*'

# Redirector files
redirs:
  - 'redirs/**/*'

# Helper scripts
helpers:
  - 'helper-scripts/**/*'

# Documentation
documentation:
  - 'README.md'
  - 'LICENSE'
  - 'VERSION'
  - 'releasenotes.txt'
  - 'images/**/*'
  - 'example-data-and-configs/**/*'

# Installer files
installer:
  - 'initial-setup.sh'
  - 'c2servers/install-c2server-*.sh'
  - 'elkserver/install-elkserver.sh'
  - 'elkserver/redelk-*.yml'
  - 'redirs/install-redir.sh'

# Docker files
docker:
  - 'elkserver/docker/**/*'

# GitHub workflows and CI/CD files
githubci:
  - '.github/**/*'
