filebeat.inputs:
- type: log
  scan_frequency: 5s
  enabled: true
  fields_under_root: true
  paths:
    - /opt/*/poshc2_server.log
  include_lines: ['(.*)implant\s+connected:\s+','(0[1-9]|[12]\d|3[01])/(0[1-9]|1[0-2])/[12]\d{3}\s+([0-1][0-9]|[2][0-3]):([0-5][0-9]):([0-5][0-9]):(.*?)','Download\s+file\s+part\s+(.*?)','Screenshot\s+captured:\s+(.*?)','(.*?)\:(.*?)\s+\|\s+Time:(.*?)\s+\|\s+PID:(.*?)\s+\|\s+Sleep:(.*?)\s+\|\s+(.*?)\s+@\s+(.*?)\s+\((.*?)\)\s+\|\s+URL\:(.*?)']
  fields:
    infralogtype: rtops
    c2program: poshc2
    c2logtype: events

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false  

setup.template.settings:
  index.number_of_shards: 3

name: "@@HOSTNAME@@"
fields_under_root: true
fields:
  attackscenario: @@ATTACKSCENARIO@@
harvester.limit: 1

output.logstash:
  hosts: ["@@HOSTANDPORT@@"]
  ssl.certificate_authorities: ["/etc/filebeat/redelkCA.crt"]


