name: Build docker elasticsearch image (prd)

on:
  push:
    tags:
      - '*'
    paths:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Prepare
        id: prepare
        run: |
          if [[ "x$DOCKER_REPO" == "x" ]]; then
            DOCKER_REPO=outflanknl
          fi
          DOCKER_IMAGE="${DOCKER_REPO}/redelk-elasticsearch"
          echo ::set-output name=docker_image::${DOCKER_IMAGE}
          echo ::set-output name=docker_repo::${DOCKER_REPO}
          echo ::set-output name=build_args::BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') \
            VCS_REF=${GITHUB_SHA::8}
        env:
          DOCKER_REPO: ${{ secrets.DOCKER_REPO }}
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: ${{ steps.prepare.outputs.docker_image }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        if: ${{ github.event_name != 'pull_request' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Cache Docker layers
        uses: actions/cache@v2
        id: cache
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-elasticsearch-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-elasticsearch-
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: elkserver/docker/redelk-elasticsearch
          file: ./elkserver/docker/redelk-elasticsearch/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          build-args: ${{ steps.prepare.outputs.build_args }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache
