name: Lint - Python

on:
  push:
    paths:
      - 'elkserver/docker/redelk-base/redelkinstalldata/scripts/**'
      - .github/workflows/lint.yml
  pull_request:
    paths:
      - 'elkserver/docker/redelk-base/redelkinstalldata/scripts/**'
      - .github/workflows/lint.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8.10'
        architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black
        pip install -r elkserver/docker/redelk-base/redelkinstalldata/scripts/requirements.txt
    - name: Analysing the code with black
      run: |
        black --check --diff --color elkserver/docker/redelk-base/redelkinstalldata/scripts 
