name: Pylint

on:
  push:
    paths:
      - 'elkserver/docker/redelk-base/redelkinstalldata/scripts/**'
      - .github/workflows/pylint.yml
  pull_request:
    paths:
      - 'elkserver/docker/redelk-base/redelkinstalldata/scripts/**'
      - .github/workflows/pylint.yml

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint Pillow
        pip install -r elkserver/docker/redelk-base/redelkinstalldata/scripts/requirements.txt
    - name: Analysing the code with pylint
      run: |
        find elkserver/docker/redelk-base/redelkinstalldata/scripts -not -path '*/Chameleon/*' -name '*.py' -print0 | xargs -0 -i sh -c 'echo pylint {}; PYLINTRC=$(pwd)/elkserver/docker/redelk-base/redelkinstalldata/scripts/.pylintrc pylint {}'
